runtime: python 37
env_variables:
  CLOUD_SQL_USERNAME: command
  CLOUD_SQL_PASSWORD: Thosearemine321
  CLOUD_SQL_DATABSE_NAME: commandsdb
  CLOUD_SQL_CONNECTION_NAME: aerobic-orbit-356520:us-central1:command
